### ISSUE TITLE
Trying to use no-cors mode.

### ISSUE THREAD

**Issue by dchaur** [bevacqua/scrape-metadata#1]
Hi,

I'm trying to use no-cors mode due this error:
No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4200' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
I've tried:
scrape(link.href, { mode: 'no-cors' }, (err, meta) => {
But it doesn't work...

Thanks a lot.

**Comment by bevacqua** [comment]
This is meant for server-side use. Client-side use is unsupported unless someone really wants it and then works on it to make it decent enough that I'd support it. I'd suggest setting up an `/scrape` or some such endpoint which receives the resource you want scraped on the client, and returns the response from this package.

**Comment by dchaur** [comment]
Thanks a lot for your quick answer, I found a Chrome plugin Allow-control-Allow-Origin to allow scrap sites using my localhost environment.
